### ISSUE TITLE
personal domain for mean.example.com is not as easy as changing to mean.theircynthia.com in all instructions

### ISSUE THREAD

**Issue by publishct** [microtrain/bootcamp#8]
The only way that I could get my mean.theircynthia.com to serve with httpd was by going into that vhost's conf file and replacing 127.0.0.102 with an asterisk * and then also adding another virtual host below in the same file for port 443 following the same format with the asterisk 

So tomorrow I'll have to figure out how to serve mean.theircynthia.com and also get access to my default 80 and 443 for localhost purposes 

Even though it's messed up I finally got my mean.theircynthia.com to serve up after like 15+ hours of trying different things because simply replacing mean.example.com with mean.theircynthia.com in all instructions and then pointing an A record to my public IP did not work... at all

ALSO 
I included this option in my /etc/apache2/apache2.conf
```
# To set default VirtualHost, include it before anything else.
IncludeOptional sites-enabled/mean.theircynthia.com.conf
```
And finally I commented out the DocRoot /var/www in both the default-ssl.conf and the 000-default.conf

**Comment by swasgrafx** [comment]
Walking through 13-Express from start to finish and having a different mean.YOUR-SITE.com name should not produce any local errors as the project runs on Express through http://localhost:3000/
mean.YOUR-SITE.com should have been added in;
etc/apache2/sites-available
etc/apache2/sites-enabled
/etc/hosts

From reading above, you would like to use your computer to host your website, adding your IP to Domain Registrar? The 13-Express Chapter was intended to provide server-side functionality to our JavaScript project and use it to spin up a web server via NodeJS and not specifically host the project.

Entries created in hosts file are for local testing, but that will work only from the machine with those hosts entries. If trying to use your laptop as the "server" and serve mean.YOUR-SITE.com to the outside world, there are other steps to take in configuring Apache and creating a simple hosting configuration. This process was indirectly discussed throughout the class on day one, setting up LAMP server on AWS.
